e:
 conf:
    attachmentBaseDirectory : ./upload
    defaultLocale: zh_CN
    supportLocales: 
                 - en_US
                 - zh_CN 
    defaultPage: readme.html
       
    staticMappings:
         /log-ui/**: 
            - classpath:/static/
 
spring:
   application:
            name: log-ui
   
server:
    port: 29090
    tomcat:
      uri-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 指定注册中心的地址
  instance:
    preferIpAddress: true

     
logging:
    path: ./logs
    file: ./logs/log-ui.log


